---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users":
    post:
      summary: Registers a new user
      tags:
      - users
      parameters: []
      responses:
        '200':
          description: created successfuly
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password
  "/users/sign_in":
    post:
      summary: signs in a user
      tags:
      - user
      parameters: []
      responses:
        '200':
          description: signed in successfuly
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
